AWSTemplateFormatVersion: 2010-09-09
Description: An example CloudFormation template for Fargate.
Parameters:
  
  # Certificate:
  #   Type: String
  #   Default: 'arn:aws:acm:us-east-2:920048411410:certificate/05bc00c7-f3b2-4e0f-85a6-508b735facd4'
  Image:
    Type: String
    Default: 450852217355.dkr.ecr.us-east-1.amazonaws.com/spring-boot:latest
  ServiceName:
    Type: String
    Default: MyService
  ContainerPort:
    Type: Number
    Default: 8090

  LoadBalancerPort:
    Type: Number
    Default: 80
  HealthCheckPath:
    Type: String
    Default: /
  
  MinContainers:
    Type: Number
    Default: 1
  # for autoscaling
  MaxContainers:
    Type: Number
    Default: 2
  # target CPU utilization (%)
  AutoScalingTargetValue:
    Type: Number
    Default: 50
 
 
 
Resources:
  
  ## Cluster
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  
  ## Task Definition
  TaskDefinition1:
    Type: AWS::ECS::TaskDefinition
    
    DependsOn: LogGroup
    Properties:
      # Name of the task definition.
      Family: !Join ['', [!Ref ServiceName, TaskDefinition1]]
     
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE    
      Cpu: 1024  
      Memory: 2GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref Image
          # Environment:
          #   - Name: MYSQL_HOSTNAME
          #     Value: 
          #       Fn::ImportValue: DBEndPoint

          #   - Name: MYSQL_PORT
          #     Value: 3306

          #   - Name: MYSQL_DATABASE
          #     Value: bootexample

          #   - Name: MYSQL_USER
          #     Value: spring

          #   - Name: MYSQL_PASSWORD
          #     Value: spring@123

          #   - Name: MYSQL_ROOT_PASSWORD
          #     Value: root@123
              
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          # CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  
  ## Role needed by ECS
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
        
  ## Role for the containers
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, TaskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
     
  ## A Role needed for auto scaling
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, AutoScalingRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'

  ## Container Security Group
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref ServiceName, ContainerSecurityGroup]]
      VpcId: 
        Fn::ImportValue: VPC                                                                   #############################3
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
        - IpProtocol: tcp
          FromPort: 0 ##########!Ref ContainerPort
          ToPort: 65535 #############!Ref ContainerPort
          CidrIp: 0.0.0.0/0
          #SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

          

  ## LoadBalancer Security Group
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref ServiceName, LoadBalancerSecurityGroup]]
      VpcId: 
        Fn::ImportValue: VPC                                                                   ###################################
    
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  
  ## Service
  Service:
    Type: AWS::ECS::Service
    
    DependsOn:
      - ListenerHTTP
    Properties: 
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition1
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue: PrivateSubnet1  #private                      ################################################
            - Fn::ImportValue: PrivateSubnet2
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  ###########################################################################################################################
# ##Taskfenition for Mysql
  TaskDefinitionmysql:
    Type: AWS::ECS::TaskDefinition
    
    DependsOn: LogGroup
    Properties:
      # Name of the task definition.
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionmysql]]
     
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
    
      Cpu: 1024
      Memory: 2GB


          
      # A role needed by ECS.
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: mysqll
          Image: 450852217355.dkr.ecr.us-east-1.amazonaws.com/mysqll:latest
          PortMappings:
            - ContainerPort: 3306
          Environment:
            - Name: MYSQL_DATABASE
              Value: bootexample

            - Name: MYSQL_USER
              Value: spring

            - Name: MYSQL_PASSWORD
              Value: spring@123

            - Name: MYSQL_ROOT_PASSWORD
              Value: root@123
          # CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  service12:
    Type: AWS::ECS::Service
    
    DependsOn:
      - ListenerHTTP
    Properties: 
      ServiceName: mysql
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionmysql
    
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      # HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue: PrivateSubnet1  #private
            - Fn::ImportValue: PrivateSubnet2
          SecurityGroups:
            - !Ref ContainerSecurityGroup

            #########################################################################################
  
  ## Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 40
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckTimeoutSeconds: 30
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Join ['', [!Ref ServiceName, TargetGroup]]
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 
      TargetType: ip
      VpcId: 
        Fn::ImportValue: VPC                             ########################################################
  
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref LoadBalancerPort
      Protocol: HTTP

    
      # Certificates:
      #   - CertificateArn: !Ref Certificate
  
  ## Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Name: !Join ['', [!Ref ServiceName, LoadBalancer]]
      # "internal" is also an option
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets:
        - Fn::ImportValue: PublicSubnet1                                   #public  ###################################################################
        - Fn::ImportValue: PublicSubnet2
  
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinition]]
  
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: !Ref MinContainers
      MaxCapacity: !Ref MaxContainers
      ResourceId: !Join ['/', [service, !Ref Cluster, !GetAtt Service.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      # AWS Identity and Access Management (IAM)
      RoleARN: !GetAtt AutoScalingRole.Arn
 
  AutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join ['', [!Ref ServiceName, AutoScalingPolicy]]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        TargetValue: !Ref AutoScalingTargetValue
